#!/bin/bash

if [ ! -d "tests/TestCase" ]
then
    repo="https://github.com/antaresbr/php-testcase.git"
    git clone "${repo}" "tests/TestCase"
    [ $? -eq 0 ] || { echo "ERROR: Fail to clone ${repo}"; exit 1; }

    composer dump-autoload
    [ $? -eq 0 ] || { echo "ERROR: Fail dump composer autoload"; exit 1; }
fi

./vendor/bin/phpunit --colors --testdox "$@"
